### ISSUE TITLE
data used in benchmark of mouse embryo

### ISSUE THREAD

**Issue by giovp** [dpeerlab/ENVI#5]
in the paper it is mentioned that 
"""
the authors used seqFISH to image 351 genes in tissue sections of mouse embryos from embryonic day 8.75 (E8.75), resulting in 57,536 cells imaged. This data was paired with scRNA-seq data collected from mouse at E8.75 consisting of 12,995 cells
"""
but the original publication https://www.nature.com/articles/s41586-019-0933-9 claims to only have single cell until E8.5, whereas indeed the spatial was at E8.75 https://www.nature.com/articles/s41587-021-01006-2. Is that a typo in the paper and the E8.5 were used from Pijuan Sala et al, or were you able to have access to such dataset and if so is it planned to also make it public?

Thank you in advance!

H/T @selmanozleyen

**Comment by DoronHav** [comment]
Hi! 

We used the scRNA-seq data you referenced from Pijuan Sala et al. This is indeed a typo, thanks for alerting us!
