### ISSUE TITLE
MSSI implementation not available

### ISSUE THREAD

**Issue by giovp** [dpeerlab/ENVI#6]
Hi,

we would like to reproduce some of the results of the paper but we can't find the MSSI calculation in the repo. It would be useful to have such implementation, any chance that it can be shared?

Thank you in advance,

HT @selmanozleyen

**Comment by soerenab** [comment]
Any update here? I would also be interested in this implementation. Thank you!

**Comment by DoronHav** [comment]
Hi! We have just released mssi as a pip installable package. 

Please see details in: https://github.com/dpeerlab/mssi/tree/main
