### ISSUE TITLE
 [Question] Analyzing CosMx data

### ISSUE THREAD

**Issue by ccruizm** [dpeerlab/ENVI#60]
Good day! 

I would like to use your tool to analyze CosMx data. I have several FOVs (20 FOVs per slide/2 slides in total) for different biological replicates. Could I process them all at once? or do I need to subset each FOV independently and run ENIV on each? I want to determine niches that are common across all FOV. What would you suggest would be the best approach in this case?

Your advice/suggestions are very welcome! thank you in advance.

**Comment by DoronHav** [comment]
Hey! 

You can run ENVI on all of them at once, just make sure you add the relevant 'batch_key' parameter in the ENVI initialization or else you will encounter errors.  

https://scenvi.readthedocs.io/en/latest/ENVI.html

**Comment by ccruizm** [comment]
Thanks for your reply! Another question, I need to exclude some FOVs since they belong to other tumor entities. How do you recommend to do it?

Thanks again!
