### ISSUE TITLE
CODEX (PhenoCycler) + scRNA-seq

### ISSUE THREAD

**Issue by qu4drupole** [dpeerlab/ENVI#62]
I have CODEX data (1.8m cells x 38 features), where the 38 features are also measured in the expression data (24k cells x 25359 features). I use default parameters for everything, except I've tried a few variations with training (e.g. larger batches, more steps). As a first step in evaluating the results, I look at the UMAP calculated from the ENVI latent space. I was expecting to see "integration" in the graph, but, based on that visual heuristic, I'm wary to trust any imputation or inference. Do you see a red flag here? Do you have any tips to improve    performance? Is CODEX data not appropriate for this method?

![latent_umap_v1](https://github.com/dpeerlab/ENVI/assets/2091870/d39da770-c237-41c8-99b8-cf39aa5969ae)

**Comment by DoronHav** [comment]
ENVI is intended for high-res spatial transcriptomics data (MERFISH, XENIUM, etc') and was not designed with protein imaging in mind. With default parameters, ENVI assumes a Poisson distribution of the counts in the spatial dataset, which CODEX presumably does not follow and can lead to suboptimal performance such as what you're seeing.

One solution could be to z-score your single-cell and CODEX datasets are run ENVI using the Guassian distribution, like so:

```

envi_model = scenvi.ENVI(spatial_data = st_data, sc_data = sc_data, spatial_dist='norm', sc_dist='norm',
                                             num_cov_genes = -1,  # use all genes in the codex data
                                            )
```

Let us know how it goes!

**Comment by qu4drupole** [comment]
Thanks for the tip! I think there's improvement, but it's still pretty far from integrated. I think CODEX data just isn't appropriate for COVET--in fact, I don't think CODEX data is appropriate for most single-cell methods. Often, the most important piece of information comes down to a single marker, so things like covariance aren't meaningful and could be misleading.

![latent_umap_v3](https://github.com/dpeerlab/ENVI/assets/2091870/60018278-f013-41d8-af51-56fc419623d5)

On a separate note, I had to make a few edits:

1. In my version of scenvi (0.3.3), the `mean_sc()` method of `ENVI()` assigns an object called `sc_neurons` when using 'norm' and 'pois'. I assume this was supposed to be 'sc_inp'. This is fixed in your GitHub repo, but wanted to let you know it's out there.
2. I used log-transformed, z-scored data. The first step of `CalcCovMats()` in the utilities runs a log-transform. You should add a check for whether or the not the data have already been transformed. In my case, I just checked whether there were any negative values.
 
Awesome work! We just generated MERSCOPE data from these same tissue, so I'm excited to see the COVET results from those experiments!

**Comment by DoronHav** [comment]
thanks for the notes! we have just patched our package based on them. 

Hopefully you will have more success with ENVI using MERSCOPE data!
